### ISSUE TITLE
x86-64 throws BadDataError on basic disassembly

### ISSUE THREAD

**Issue by Jumboperson** [StarCrossPortal/sleighcraft#23]
While attempting to use sleighcraft for x86-64 disassembly I've run into a problem with BadDataErrors being thrown on valid code.

Code to reproduce when using the python package:
```python
from bincraft import Sleigh
# Opcodes for xor rax, rax in x86-64
# Also for dec eax; xor eax, eax in x86
code = [72, 49, 192]

# x86 test case
sleigh = Sleigh("x86", code)
print(sleigh.disasm(0)) # works

sleigh = Sleigh("x86-64", code)
print(sleigh.disasm(0)) # fails with OSError: cpp exception: BadDataError
```

I'm unsure as to what could be causing this issue, or if I missed a configuration step somewhere in the process.
Any feedback is appreciated.

**Comment by Escapingbug** [comment]
This should be a bug. We will be working on it shortly. Thanks!
